### ISSUE TITLE
我用laravel5.8安装失败。解决一下呗

### ISSUE THREAD

**Issue by huanBird** [imzhi/jf-admin#7]
<img width="1577" alt="图片" src="https://user-images.githubusercontent.com/33741256/70103995-a9911b80-1677-11ea-9e8a-e2d51ab32b47.png">
<img width="1608" alt="图片" src="https://user-images.githubusercontent.com/33741256/70104006-b150c000-1677-11ea-99e9-411dc2537e5b.png">

**Comment by huanBird** [comment]
好像是标示不要安装 laravel5.8 ？什么情况？

**Comment by imzhi** [comment]
jf-admin依赖的其它扩展包的版本约束有问题，我修复下

**Comment by huanBird** [comment]
嗯嗯 麻烦大佬啦

**Comment by huanBird** [comment]
解决了吗？

**Comment by huanBird** [comment]
@imzhi

**Comment by imzhi** [comment]
解决了，composer require imzhi/jf-admin ^1.3.4

**Comment by huanBird** [comment]
谢谢大佬
