### ISSUE TITLE
laravel5.8执行最后一步的安装任务出错

### ISSUE THREAD

**Issue by huanBird** [imzhi/jf-admin#8]
<img width="1679" alt="图片" src="https://user-images.githubusercontent.com/33741256/70107730-52447880-1682-11ea-95c1-17c5703ba6c0.png">

**Comment by huanBird** [comment]
常规错误：3780外键约束“ permission_extras_permission_id_foreign”中的引用列“ permission_id”和引用列“ id”不兼容。

**Comment by imzhi** [comment]
修复了。需要重新安装下包并且手动删除下数据

1. 删除2019_07_04_141217_create_permission_extras_table.php这个文件
3. 删除数据库中的permission_extras表
2. composer require imzhi/jf-admin ^1.1
3. php artisan vendor:publish --provider="Imzhi\JFAdmin\JFAdminServiceProvider"
4. php artisan jfadmin:install

**Comment by imzhi** [comment]
修复了。需要重新安装下包并且手动删除下数据

1. 删除2019_07_04_141217_create_permission_extras_table.php这个文件
3. 删除数据库中的permission_extras表
2. composer require imzhi/jf-admin ^1.1
3. php artisan vendor:publish --provider="Imzhi\JFAdmin\JFAdminServiceProvider"
4. php artisan jfadmin:install

**Comment by huanBird** [comment]
那个大佬 能可以加一下qq 或者微信吗？我还有一些问题需要问一下，耽误您一些时间

**Comment by imzhi** [comment]
如果是扩展包有问题直接开issue，我在这里回复。要么在learnku里私信我，也可以看到

**Comment by huanBird** [comment]
好的

**Comment by huanBird** [comment]
我把包 卸载啦。重新composer安装 是要安装新版本是吧。composer require imzhi/jf-admin ^1.1 这个我没有看懂？我新安装需要安装1.1版本吗？

**Comment by imzhi** [comment]
composer require imzhi/jf-admin ^1.1  这个的意思是安装 1.x.x 里的最新版本，并不是安装1.1版本

**Comment by huanBird** [comment]
哦。 好的
